PI := $(HOME)/.pi/agent
CLAUDE_CONFIG_DIR ?= $(HOME)/.claude
CODEX_HOME ?= $(HOME)/.codex
AGENTS := $(HOME)/.agents
XDG_CONFIG_HOME ?= $(HOME)/.config
MCP_CONFIG := $(XDG_CONFIG_HOME)/mcp/mcp.json
OPENCODE_CONFIG_DIR?= $(XDG_CONFIG_HOME)/opencode
LOCAL_BIN := $(HOME)/.local/bin

OPEN_COMPUTER_USE_VERSION ?= 0.3.1
OPEN_COMPUTER_USE_TARBALL := https://registry.npmjs.org/open-computer-use/-/open-computer-use-$(OPEN_COMPUTER_USE_VERSION).tgz
RUNTIME_ENV := $(AGENTS)/bin/.cache/runtime-env

.PHONY: all pi mcp claude-code opencode codex open-computer-use open-computer-use\:a11y

all: mcp pi claude-code opencode codex open-computer-use

pi: pi\:settings pi\:extensions pi\:prompts pi\:themes pi\:skills

pi\:settings:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/.pi/agent/settings.json" "$(PI)/settings.json"

pi\:extensions:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/.pi/agent/extensions" "$(PI)/extensions"

pi\:prompts:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/.pi/agent/prompts" "$(PI)/prompts"

pi\:themes:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/.pi/agent/themes" "$(PI)/themes"

pi\:skills:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/skills" "$(PI)/skills"

pi\:web-search:
	mkdir -p "$(PI)"
	ln -sfn "$(AGENTS)/.pi/web-search.json" "$(PI)/web-search.json"

mcp:
	mkdir -p "$(dir $(MCP_CONFIG))"
	ln -sfn "$(AGENTS)/.mcp.json" "$(MCP_CONFIG)"

claude-code: claude-code\:skills claude-code\:settings

claude-code\:skills:
	mkdir -p "$(CLAUDE_CONFIG_DIR)"
	ln -sfn "$(AGENTS)/skills" "$(CLAUDE_CONFIG_DIR)/skills"

claude-code\:settings:
	mkdir -p "$(CLAUDE_CONFIG_DIR)"
	ln -sfn "$(AGENTS)/claude-code/settings.json" "$(CLAUDE_CONFIG_DIR)/settings.json"

opencode: opencode\:config opencode\:tui opencode\:skills

opencode\:config:
	mkdir -p "$(OPENCODE_CONFIG_DIR)"
	ln -sfn "$(AGENTS)/opencode/opencode.json" "$(OPENCODE_CONFIG_DIR)/opencode.json"

opencode\:tui:
	mkdir -p "$(OPENCODE_CONFIG_DIR)"
	ln -sfn "$(AGENTS)/opencode/tui.json" "$(OPENCODE_CONFIG_DIR)/tui.json"

opencode\:skills:
	mkdir -p "$(OPENCODE_CONFIG_DIR)/skills"
	ln -sfn $(AGENTS)/skills/* "$(OPENCODE_CONFIG_DIR)/skills/"

codex: codex\:config codex\:skills

codex\:config:
	mkdir -p "$(CODEX_HOME)"
	ln -sfn "$(AGENTS)/codex/config.toml" "$(CODEX_HOME)/config.toml"

codex\:skills:
	mkdir -p "$(CODEX_HOME)/skills"
	ln -sfn $(AGENTS)/skills/* "$(CODEX_HOME)/skills/"

open-computer-use: open-computer-use\:binary open-computer-use\:runtime-env open-computer-use\:wrapper open-computer-use\:shims

open-computer-use\:binary:
	mkdir -p "$(AGENTS)/bin" "$(AGENTS)/bin/.cache"
	curl -fsSL "$(OPEN_COMPUTER_USE_TARBALL)" -o "$(AGENTS)/bin/.cache/open-computer-use.tgz"
	rm -rf "$(AGENTS)/bin/.cache/extract"
	mkdir -p "$(AGENTS)/bin/.cache/extract"
	tar xzf "$(AGENTS)/bin/.cache/open-computer-use.tgz" -C "$(AGENTS)/bin/.cache/extract"
	install -Dm755 "$(AGENTS)/bin/.cache/extract/package/dist/linux/amd64/open-computer-use" "$(AGENTS)/bin/open-computer-use-native"

open-computer-use\:runtime-env:
	mkdir -p "$(AGENTS)/bin/.cache"
	nix build "$(AGENTS)"#open-computer-use-runtime-env --no-link --print-out-paths 2>/dev/null | tail -n 1 > "$(AGENTS)/bin/.cache/runtime-env-path"
	rm -rf "$(RUNTIME_ENV)"
	ln -sfn "$$(cat "$(AGENTS)/bin/.cache/runtime-env-path")" "$(RUNTIME_ENV)"

open-computer-use\:wrapper:
	printf '%s\n' \
	  '#!/usr/bin/env bash' \
	  '# Generated by `make open-computer-use`; provides the Nix runtime env' \
	  '# (python3 with PyGObject + AT-SPI/GTK typelibs) before the binary runs.' \
	  'env_file="$(AGENTS)/bin/.cache/runtime-env/activate"' \
	  'if [[ -f "$${env_file}" ]]; then' \
	  '  # shellcheck disable=SC1090' \
	  '  source "$${env_file}"' \
	  'fi' \
	  'exec "$(AGENTS)/bin/open-computer-use-native" "$$@"' \
	  > "$(AGENTS)/bin/open-computer-use"
	chmod +x "$(AGENTS)/bin/open-computer-use"

open-computer-use\:shims:
	mkdir -p "$(LOCAL_BIN)"
	ln -sfn "$(AGENTS)/bin/open-computer-use" "$(LOCAL_BIN)/open-computer-use"
	ln -sfn "$(AGENTS)/bin/open-computer-use" "$(LOCAL_BIN)/ocu"

open-computer-use\:a11y:
	mkdir -p "$(XDG_CONFIG_HOME)/systemd/user"
	{ \
	  echo '[Unit]'; \
	  echo 'Description=AT-SPI accessibility bus launcher (needed by open-computer-use on Linux)'; \
	  echo; \
	  echo '[Service]'; \
	  printf 'ExecStart=%s/bin/at-spi-bus-launcher\n' "$$(cat "$(AGENTS)/bin/.cache/runtime-env-path")"; \
	  echo 'Restart=on-failure'; \
	  echo; \
	  echo '[Install]'; \
	  echo 'WantedBy=default.target'; \
	} > "$(XDG_CONFIG_HOME)/systemd/user/open-computer-use-a11y.service"
	systemctl --user daemon-reload
	systemctl --user enable --now open-computer-use-a11y.service
